### PR TITLE
Some Go Implementations

### PR DESCRIPTION
**Pull request by crhntr**
Hello Professor Soltys,

I just spent a few minutes copying some code from what I did last semester and refactoring so it will work with your directory structure.

This PR contains implementations for: division, Euclid's GCD (both the basic and extended), and palindromes.

I am following the following standard:
* For each folder in your algorithms directory, I am creating a go package. The package name is as
close as possible to the parent directory name "1.1_Division" -> "division" such that the package name makes sense as a go package name.
* The package will at least have a function called "Alg" that takes and returns values whose definition best suites the algorithm. This function will be declared in a file called alg.go.
* 100% Test Coverage. The test files should have the alg_test.go filename.

For example:
```go
q, r := division.Alg(6, 3)
fmt.Printf("q: %d, r: %d\n", q, r)
// should output: q: 2 r: 0
```

I followed a similar file naming convention in the high school course that I taught last semester and
created some utilities for generating handout PDFs and slide decks.

If you like how these are organized, I will be happy to copy the rest of the Go implementations over.

Thanks for the PR review,
Chris (@crhntr)

### CODE REVIEW

**Comment by crhntr** [comment]
Where possible, I am adding a Verbose function that displays loop invariant and any other variables that change. See the division.Verbose for an example.

**Comment by crhntr** [comment]
I decided to do these first three as a batch to show the organization and convention. Future pull requests will be per algorithm.

**Comment by crhntr** [comment]
The primary reason I am naming the functions implementing the algorithm alg is to avoid clumsy function calls from another package.

```go
euclids.Alg(/* args */)
// is preferable to
euclids.Euclids(/* args */)
```

**Comment by michaelsoltys** [comment]
This is very cool @crhntr Thank you so much for working on this! We should talk.

**Pull request merged**
